export const SCENE_PRESETS: Array<{
  name: string;
  description?: string;
  type?: string;
  backgroundPrompt?: string;
  lighting?: string;
  mood?: string;
  suggestedAspectRatio?: string;
  qualityPreset?: string;
  category?: string;
  tags?: string;
}> = [
  {
    name: 'Studio Soft Light',
    description: 'Clean studio setup with soft, even lighting and neutral background.',
    type: 'PRESET',
    backgroundPrompt: 'seamless neutral studio backdrop',
    lighting: 'soft studio lighting, even illumination, gentle shadows',
    mood: 'professional',
    suggestedAspectRatio: '4:5',
    qualityPreset: 'high',
    category: 'studio',
    tags: 'studio, e-commerce, clean, neutral',
  },
  {
    name: 'Minimal Grey',
    description: 'Minimal e-commerce shot on a flat grey background.',
    type: 'PRESET',
    backgroundPrompt: 'plain mid-grey studio background',
    lighting: 'soft directional studio light, subtle shadows',
    mood: 'minimal',
    suggestedAspectRatio: '4:5',
    qualityPreset: 'high',
    category: 'minimal',
    tags: 'e-commerce, minimal, grey, clean',
  },
  {
    name: 'Beach Golden Hour',
    description: 'Warm and natural beach scene during golden hour.',
    type: 'PRESET',
    backgroundPrompt: 'sandy beach, sea waves in distance, low golden sun near horizon',
    lighting: 'golden hour sunlight, warm tones, soft long shadows',
    mood: 'relaxed',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'beach',
    tags: 'beach, sunset, golden hour, warm, vacation',
  },
  {
    name: 'Pool Daylight',
    description: 'Modern poolside scene with bright natural light.',
    type: 'PRESET',
    backgroundPrompt: 'clear swimming pool, pool deck, minimal modern furniture',
    lighting: 'bright outdoor daylight, crisp reflections',
    mood: 'fresh',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'pool',
    tags: 'pool, resort, summer, fresh, blue water',
  },
  {
    name: 'Luxury Penthouse',
    description: 'High-end interior with large windows and city view.',
    type: 'PRESET',
    backgroundPrompt: 'luxury penthouse living room with big windows and city skyline view',
    lighting: 'soft interior light mixed with window daylight',
    mood: 'luxury',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'luxury',
    tags: 'luxury, city, interior, high-end, lifestyle',
  },
  {
    name: 'Urban Rooftop',
    description: 'Outdoor rooftop scene with city skyline.',
    type: 'PRESET',
    backgroundPrompt: 'city rooftop terrace with skyline in background',
    lighting: 'natural daylight, slightly directional',
    mood: 'urban',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'urban',
    tags: 'rooftop, city, skyline, street style, urban',
  },
  {
    name: 'Indoor Bedroom Natural Light',
    description: 'Cozy bedroom scene with window light.',
    type: 'PRESET',
    backgroundPrompt: 'bright bedroom, soft bedding, large window, light curtains',
    lighting: 'soft natural window light',
    mood: 'cozy',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'indoor',
    tags: 'bedroom, cozy, natural light, lifestyle',
  },
  {
    name: 'Lifestyle Living Room',
    description: 'Modern living room for lifestyle shots.',
    type: 'PRESET',
    backgroundPrompt: 'modern living room, sofa, plants, decor elements',
    lighting: 'soft interior lighting with ambient daylight',
    mood: 'casual',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'indoor',
    tags: 'living room, lifestyle, casual, home',
  },
  {
    name: 'Minimal White Wall',
    description: 'Ultra simple white wall background.',
    type: 'PRESET',
    backgroundPrompt: 'plain white wall with subtle floor line',
    lighting: 'soft studio lighting, nearly shadowless',
    mood: 'minimal',
    suggestedAspectRatio: '4:5',
    qualityPreset: 'high',
    category: 'minimal',
    tags: 'white, studio, catalog, clean',
  },
  {
    name: 'Outdoor Garden',
    description: 'Green garden with foliage and soft sunlight.',
    type: 'PRESET',
    backgroundPrompt: 'garden with green plants and foliage in background',
    lighting: 'soft outdoor light with gentle shadows',
    mood: 'fresh',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'outdoor',
    tags: 'garden, green, natural, fresh, outdoor',
  },
  {
    name: 'Sunset Boardwalk',
    description: 'Warm boardwalk with sunset sky and distant ocean.',
    type: 'PRESET',
    backgroundPrompt: 'wooden boardwalk near the sea, sunset sky with warm tones',
    lighting: 'sunset glow, warm, soft shadows',
    mood: 'romantic',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'outdoor',
    tags: 'sunset, boardwalk, warm, romantic',
  },
  {
    name: 'Neon Urban Night',
    description: 'Moody neon-lit urban street at night.',
    type: 'PRESET',
    backgroundPrompt: 'urban street at night with neon signs and reflections',
    lighting: 'neon lighting, contrasting colors, moody shadows',
    mood: 'cinematic',
    suggestedAspectRatio: '16:9',
    qualityPreset: 'high',
    category: 'urban',
    tags: 'night, neon, cyberpunk, city, cinematic',
  },
  {
    name: 'Coastal Rocks',
    description: 'Rocky coastal scene with crashing waves.',
    type: 'PRESET',
    backgroundPrompt: 'rocky coastline with ocean waves and cloudy sky',
    lighting: 'soft daylight, misty atmosphere',
    mood: 'dramatic',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'outdoor',
    tags: 'coast, rocks, ocean, dramatic',
  },
  {
    name: 'Forest Trail',
    description: 'Lush forest trail with dappled light.',
    type: 'PRESET',
    backgroundPrompt: 'forest trail with tall trees and dappled sunlight',
    lighting: 'soft filtered light through trees',
    mood: 'natural',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'outdoor',
    tags: 'forest, nature, green, trail',
  },
  {
    name: 'Desert Dunes',
    description: 'Sand dunes under warm sunlight.',
    type: 'PRESET',
    backgroundPrompt: 'soft sand dunes with gentle ridges under warm sky',
    lighting: 'warm daylight with long shadows',
    mood: 'serene',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'outdoor',
    tags: 'desert, dunes, warm, serene',
  },
  {
    name: 'Warehouse Industrial',
    description: 'Industrial warehouse interior with texture.',
    type: 'PRESET',
    backgroundPrompt: 'industrial warehouse space, concrete floor, textured walls',
    lighting: 'directional window light, some shadows',
    mood: 'gritty',
    suggestedAspectRatio: '3:4',
    qualityPreset: 'high',
    category: 'urban',
    tags: 'industrial, warehouse, gritty, textured',
  },
];
